In [3]:
import os
os.listdir()

['.ipynb_checkpoints',
 'Customer Dimension.ipynb',
 'Customer_Dimension.csv',
 'customer_spending_tiers.csv',
 'day3.ipynb',
 'Inventory_Dimension.csv',
 'Inventory_Dimension.ipynb',
 'Product_Dimension.csv',
 'Product_Dimension.ipynb',
 'Region_Dimension.csv',
 'Sales_Fact.csv',
 'sales_fact.ipynb',
 'StadiaGear_Retail_Performance .ipynb',
 'StadiaGear_Retail_Performance_20000_Rows1.csv',
 'Untitled.ipynb',
 'Untitled1.ipynb',
 'Untitled2.ipynb']

In [4]:
import pandas as pd

sales = pd.read_csv("Sales_Fact.csv")

In [5]:
sales.head()

   TransactionID  CustomerID ProductID Region  Quantity  Revenue
0              1        3262    P02804   East         5   320.25
1              2        9453    P04325   West         3    39.06
2              3        4540    P03381  North         2   262.08
3              4        8774    P00636   East         2   299.84
4              5        9492    P00744   East         1   114.06

In [9]:
sales.columns

Index(['TransactionID', 'CustomerID', 'ProductID', 'Region', 'Quantity',
       'Revenue'],
      dtype='object')

In [11]:
sales['Date'] = pd.date_range(
    start='2024-01-01',
    periods=len(sales),
    freq='D'
)

In [12]:
sales.head()

   TransactionID  CustomerID ProductID Region  Quantity  Revenue       Date
0              1        3262    P02804   East         5   320.25 2024-01-01
1              2        9453    P04325   West         3    39.06 2024-01-02
2              3        4540    P03381  North         2   262.08 2024-01-03
3              4        8774    P00636   East         2   299.84 2024-01-04
4              5        9492    P00744   East         1   114.06 2024-01-05

In [13]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   TransactionID  20000 non-null  int64
 1   CustomerID     20000 non-null  int64
 2   ProductID      20000 non-null  object
 3   Region         20000 non-null  object
 4   Quantity       20000 non-null  int64
 5   Revenue        20000 non-null  float64
 6   Date           20000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(3), object(2)
memory usage: 1.1+ MB

In [14]:
sales.to_csv("Sales_Fact_Updated.csv", index=False)

In [15]:
sales['Date'] = pd.to_datetime(sales['Date'])

In [16]:
product = pd.read_csv("Product_Dimension.csv")
product.isnull().sum()

ProductID    0
Category     0
UnitPrice    0
dtype: int64

In [17]:
product = pd.read_csv("Product_Dimension.csv")

In [18]:
product.head()

  ProductID     Category  UnitPrice
0    P02804     Footwear      64.05
1    P04325     Footwear      13.02
2    P03381      Jerseys     131.04
3    P00636  Accessories     149.92
4    P00744     Footwear     114.06

In [19]:
product.isnull().sum()

ProductID    0
Category     0
UnitPrice    0
dtype: int64

In [20]:
missing_report = pd.DataFrame({
    'Missing Values': product.isnull().sum(),
    'Percentage': (product.isnull().sum() / len(product)) * 100
})

missing_report

           Missing Values  Percentage
ProductID               0         0.0
Category                0         0.0
UnitPrice               0         0.0

In [21]:
product.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19999 entries, 0 to 19998
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ProductID  19999 non-null  object
 1   Category   19999 non-null  object
 2   UnitPrice  19999 non-null  float64
dtypes: float64(1), object(2)
memory usage: 468.9+ KB

In [22]:
sales.to_csv("Sales_Fact_Updated.csv", index=False)

In [23]:
product.isnull().sum()

ProductID    0
Category     0
UnitPrice    0
dtype: int64